export const actiontypes = {
    GET_PRODUCT_DATA:"GET_PRODUCT_DATA",
    INC_QUANTITY:"INC_QUANTITY",
    DEC_QUANTITY:"DEC_QUANTITY",
    FILTER_PRODUCT:"FILTER_PRODUCT",
    NEW_TITLE:"NEW_TITLE",  
    ADD_TO_BASKET:"ADD_TO_BASKET",
    REMOVE_FROM_BASKET:"REMOVE_FROM_BASKET",
    EMPTY_BASKET:"EMPTY_BASKET",
    GET_CATEGORY:"GET_CATEGORY"
}